/* ============================================================================
   WheatHarvestMap - real basemap drill-down
   India -> Punjab -> project district(s) -> village -> single farmer field

   Mirrors ClearHarvestMap.jsx (the ClearHarvest rice report's map) exactly in
   structure, stack and interaction model. Only the geography and data are
   swapped for the wheat programme.
   ----------------------------------------------------------------------------
   STACK
     maplibre-gl   real vector basemap, camera animation (flyTo / fitBounds)
     framer-motion breadcrumbs, detail panel, legend transitions

   INSTALL
     npm i maplibre-gl
     import "maplibre-gl/dist/maplibre-gl.css";   // required, once, app-wide

   DATA
     wheat-fields.geo.json, wheat-boundaries.geo.json (project-district
     rectangle only), wheat-villages.json and wheat-millers.json are all
     generated from "273 Farmer Data (Clearharvest).xlsx" by
     scripts/build_fields.py - rerun that script after editing the Excel.
     No real field-boundary/KML export exists for this programme (only a
     point lat/lon per farmer), so field polygons are synthetic parcels
     built from each point + its acreage - see the script's docstring for
     the village-blob / Voronoi / erosion / jitter pipeline. `acres` on each
     feature is measured off the drawn polygon; `acresExcel` is the source
     sheet's value, kept only for reference/QA.
     wheat-boundaries.geo.json  Punjab is still a rough placeholder
                          rectangle - TODO: swap for a real state polygon
                          (dissolved from district polygons the same way
                          ClearHarvestMap.jsx handles Telangana, if needed).
                          The project-district rectangle *is* sized to the
                          real data's extent (Ludhiana + Faridkot villages).

   BASEMAP AND INDIAN BOUNDARIES - read before shipping
     The default style below (CARTO Positron) is OSM-derived and depicts the
     Line of Control in Jammu & Kashmir per international convention, not
     India's official claim line. Maps published in India are expected to show
     the full claimed boundary. For a deliverable circulating in India, point
     BASEMAP_STYLE at an India-compliant source - Mappls (MapmyIndia) or Google
     Maps served with region=IN - or clear the current basemap with your legal
     team. Swapping it is a one-line change.
============================================================================ */

import React, { useState, useRef, useEffect, useCallback } from "react";
import { motion, AnimatePresence, LayoutGroup } from "framer-motion";
// maplibre-gl v5+ ships named exports only - no default export.
import { Map as MLMap, Marker, Popup, NavigationControl, ScaleControl, setWorkerUrl } from "maplibre-gl";
// See ClearHarvestMap.jsx for why the worker + shared chunk are vendored as
// an unhashed, unbundled pair in public/maplibre/ rather than resolved by
// Vite's dependency pre-bundling.
setWorkerUrl("/maplibre/maplibre-gl-worker.mjs");

import BOUNDARIES from "./wheat-boundaries.geo.json";
import INDIA_BORDER from "./india-border.geo.json";
import FIELDS_FC from "./wheat-fields.geo.json";
import VILLAGES_DATA from "./wheat-villages.json";
import MILLERS from "./wheat-millers.json";

/* --- swap this for an India-compliant basemap before publishing in India --- */
const BASEMAP_STYLE = "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json";

/* Wheat design tokens - see the `C` palette in WheatHarvest.jsx; duplicated
   here (as ClearHarvestMap.jsx also duplicates its own `C`) so this file has
   no import-order dependency on the report component. */
const C = {
  ink: "#20180B", field: "#8A6D1F", leaf: "#C9A227", water: "#3D6B8C",
  husk: "#B4482E", clay: "#7A5230", paper: "#F7F1E1", paperDim: "#EDE3C8",
  line: "#DCCB9C", mute: "#6E624A",
};
const EASE = [0.22, 0.61, 0.36, 1];
const FONT_DATA = "'Times New Roman', Times, Georgia, 'Liberation Serif', serif";

// Real village list (126 distinct district|taluka|village groups across the
// 273 farmers) - generated by scripts/build_fields.py from the Excel sheet.
const VILLAGES = VILLAGES_DATA;

/* Palette assigned to each rice/wheat miller so the field-fill legend and
   panel stay consistent. The source sheet has no AWD/CRM column for this
   programme, so fields are coloured by procuring miller instead. Extra
   millers beyond the 5 named tokens cycle through a generated hue ramp so
   the map never silently drops a category if the roster grows. */
const MILLER_PALETTE = [C.field, C.leaf, C.husk, C.clay, C.water];
/* Hover/selected feature-state colours must never coincide with a miller's
   own colour - reusing C.leaf/C.husk here used to make some millers' fields
   look identical to any hovered or selected field. Kept as two dedicated hues outside the miller ramp. */
const HOVER_COLOR = "#2F9E77";
const SELECTED_COLOR = "#D6336C";
const MILLER_COLORS = Object.fromEntries(
  MILLERS.map((name, i) => [
    name,
    i < MILLER_PALETTE.length ? MILLER_PALETTE[i] : `hsl(${(i * 47) % 360} 55% 42%)`,
  ])
);
const millerColor = (name) => MILLER_COLORS[name] || C.mute;

/** Bounding box of a list of {lon,lat} points, for fitBounds. */
function pointBounds(points) {
  let w = 180, s = 90, e = -180, n = -90;
  points.forEach(({ lon, lat }) => {
    if (lon < w) w = lon; if (lon > e) e = lon;
    if (lat < s) s = lat; if (lat > n) n = lat;
  });
  return [[w, s], [e, n]];
}

/** Bounding box of a Polygon or MultiPolygon geometry, for fitBounds. */
function geomBounds(geom) {
  let w = 180, s = 90, e = -180, n = -90;
  const rings = geom.type === "MultiPolygon" ? geom.coordinates.flat() : geom.coordinates;
  rings.forEach((ring) =>
    ring.forEach(([x, y]) => {
      if (x < w) w = x; if (x > e) e = x;
      if (y < s) s = y; if (y > n) n = y;
    })
  );
  return [[w, s], [e, n]];
}
const boundaryGeom = (id) => BOUNDARIES.features.find((f) => f.properties.id === id).geometry;

/* Camera stops. Bounds beat hardcoded zooms - they stay correct on any
   container aspect ratio, which a fixed zoom does not. Punjab fits its
   real state polygon; district tightly fits the real village-cluster
   bounds (not the whole district shape) so 126 village pins don't crowd
   into one corner. */
const CAMERA = {
  india:     { bounds: [[68.1, 6.7], [97.4, 35.6]], padding: 40 },
  punjab:    { bounds: geomBounds(boundaryGeom("punjab")), padding: 56 },
  district:  { bounds: pointBounds(VILLAGES), padding: 48 },
};
const LEVELS = ["india", "punjab", "district", "village"];
const LEVEL_LABEL = { india: "India", punjab: "Punjab", district: "Ludhiana & Faridkot", village: "Village" };

const featById  = (id) => FIELDS_FC.features.find((f) => f.properties.id === id);
const villageFC = (key) => ({
  type: "FeatureCollection",
  features: FIELDS_FC.features.filter((f) => f.properties.village === key),
});
const villageCount = (key) => FIELDS_FC.features.filter((f) => f.properties.village === key).length;
const TOTAL_FIELDS = FIELDS_FC.features.length;
const BLOCKS = [...new Set(VILLAGES.map((v) => v.block))];
/* Use acresExcel (the source-sheet value) for the aggregate stat, not the
   drawn-polygon `acres` - that one is a synthetic geometry measurement (with
   headroom for gaps/canals baked in) and drifts above the real total. */
const TOTAL_ACRES = Math.round(FIELDS_FC.features.reduce((s, f) => s + f.properties.acresExcel, 0));
const ACRE_TO_HA = 0.404686;

/* Procurement (MT) per miller, in a fixed display order. Miller names are
   anonymised (Miller 1-4), numbered to match the traceability flow graphic. */
const MILLER_ORDER = ["Miller 1", "Miller 2", "Miller 3", "Miller 4"];
const MILLER_PROCUREMENT_MT = Object.fromEntries(
  MILLERS.map((n) => [
    n,
    FIELDS_FC.features.filter((f) => f.properties.millerName === n).reduce((s, f) => s + f.properties.procurementMt, 0),
  ])
);

/** Bounding box of a FeatureCollection, for fitBounds. */
function fcBounds(fc) {
  let w = 180, s = 90, e = -180, n = -90;
  fc.features.forEach((f) =>
    f.geometry.coordinates[0].forEach(([x, y]) => {
      if (x < w) w = x; if (x > e) e = x;
      if (y < s) s = y; if (y > n) n = y;
    })
  );
  return [[w, s], [e, n]];
}

/* One-time global keyframe for the village-pin pulsing halo (injected once,
   guarded by id, since this component owns no app-wide stylesheet). */
function ensurePulseKeyframes() {
  if (document.getElementById("wh-village-pulse-style")) return;
  const style = document.createElement("style");
  style.id = "wh-village-pulse-style";
  style.textContent = `@keyframes wh-village-pulse {
    0%   { transform: scale(0.6); opacity: 0.6; }
    70%  { transform: scale(2.3); opacity: 0; }
    100% { transform: scale(2.3); opacity: 0; }
  }`;
  document.head.appendChild(style);
}

/* ----------------------------------------------------------------------------
   MAP
   One MapLibre instance for the whole drill-down. Layers are added once on
   load; level changes only move the camera and toggle layer visibility, which
   is far smoother than tearing sources down and rebuilding them.
---------------------------------------------------------------------------- */
function DrillMap({ level, village, focusedDistrict, selected, onPickState, onPickVillage, onPickField, onHoverField, onZoomToField, onFocusDistrict }) {
  const holder = useRef(null);
  const map = useRef(null);
  const markers = useRef([]);
  const [ready, setReady] = useState(false);
  const popup = useRef(null);
  const levelRef = useRef(level);
  const villageRef = useRef(village);
  const focusedDistrictRef = useRef(focusedDistrict);
  useEffect(() => { levelRef.current = level; }, [level]);
  useEffect(() => { villageRef.current = village; }, [village]);
  useEffect(() => { focusedDistrictRef.current = focusedDistrict; }, [focusedDistrict]);

  /** Re-fit the camera to whatever the current drill level should be
   *  looking at, reading level/village/focusedDistrict off refs so it can
   *  be called imperatively (from a ResizeObserver) as well as from the
   *  level-change effect below - both need the exact same "what should be
   *  on screen right now" logic. */
  const refitCamera = useCallback((m, opts = {}) => {
    const lvl = levelRef.current;
    if (lvl === "village" && villageRef.current) {
      m.fitBounds(fcBounds(villageFC(villageRef.current)), { padding: 70, duration: 0, essential: true, ...opts });
    } else if (lvl === "district" && focusedDistrictRef.current) {
      const districtVillages = VILLAGES.filter((v) => v.district === focusedDistrictRef.current);
      m.fitBounds(pointBounds(districtVillages.length ? districtVillages : VILLAGES), { padding: 60, duration: 0, essential: true, ...opts });
    } else {
      const cam = CAMERA[lvl] || CAMERA.india;
      m.fitBounds(cam.bounds, { padding: cam.padding, duration: 0, essential: true, ...opts });
    }
  }, []);

  /* --- init ------------------------------------------------------------- */
  useEffect(() => {
    if (map.current) return;
    ensurePulseKeyframes();
    const m = new MLMap({
      container: holder.current,
      style: BASEMAP_STYLE,
      bounds: CAMERA.india.bounds,
      fitBoundsOptions: { padding: CAMERA.india.padding },
      attributionControl: { compact: true },
      dragRotate: false,
      pitchWithRotate: false,
      maxZoom: 17,
    });
    map.current = m;
    m.on("error", (e) => console.error("MapLibre error:", e?.error || e));
    m.addControl(new NavigationControl({ showCompass: false }), "bottom-right");
    m.addControl(new ScaleControl({ maxWidth: 90, unit: "metric" }), "bottom-left");
    popup.current = new Popup({ closeButton: false, closeOnClick: false, offset: 12, className: "wh-popup" });

    m.on("load", () => {
      const bd = (id) => ({
        type: "Feature",
        properties: {},
        geometry: BOUNDARIES.features.find((f) => f.properties.id === id).geometry,
      });

      /* India - national outline, always on, so the country reads clearly
         at every drill level (not just while zoomed out on it). Dissolved
         from state polygons by scripts/build_india_border.mjs - see that
         file's header for the same OSM/LoC-convention caveat noted above
         for the basemap; swap for a surveyor-general boundary before this
         ships to print. */
      m.addSource("india", { type: "geojson", data: INDIA_BORDER });
      m.addLayer({ id: "in-line", type: "line", source: "india",
        paint: { "line-color": C.husk, "line-width": 2.2 } });

      /* Punjab - the clickable state */
      m.addSource("punjab", { type: "geojson", data: bd("punjab") });
      m.addLayer({ id: "pb-fill", type: "fill", source: "punjab",
        paint: { "fill-color": C.field, "fill-opacity": 0.34 } });
      m.addLayer({ id: "pb-line", type: "line", source: "punjab",
        paint: { "line-color": C.field, "line-width": 1.8 } });

      /* project districts - Ludhiana and Faridkot are real, non-adjacent
         districts (kept as two separate features, each carrying its own
         districtName) so a click can tell which one it landed on and zoom
         tighter into just that district's villages. */
      const districtsFC = {
        type: "FeatureCollection",
        features: BOUNDARIES.features.filter((f) => f.properties.id.startsWith("district-")),
      };
      m.addSource("project-district", { type: "geojson", data: districtsFC });
      m.addLayer({ id: "pd-fill", type: "fill", source: "project-district",
        paint: { "fill-color": C.husk, "fill-opacity": 0 } });
      m.addLayer({ id: "pd-line", type: "line", source: "project-district",
        paint: { "line-color": C.husk, "line-width": 2, "line-opacity": 0 } });

      /* farmer fields - one source, filtered per village. Fill colour keys
         off the procuring miller (no AWD/CRM column exists for this
         programme's sheet); selected/hover feature-state always wins. */
      m.addSource("fields", { type: "geojson", data: FIELDS_FC, promoteId: "id" });
      m.addLayer({
        id: "fld-fill", type: "fill", source: "fields", filter: ["==", ["get", "village"], ""],
        paint: {
          "fill-color": [
            "case",
            ["boolean", ["feature-state", "selected"], false], SELECTED_COLOR,
            ["boolean", ["feature-state", "hover"], false], HOVER_COLOR,
            ["match", ["get", "millerName"], ...MILLERS.flatMap((n) => [n, millerColor(n)]), C.mute],
          ],
          "fill-opacity": [
            "case",
            ["boolean", ["feature-state", "selected"], false], 0.95,
            ["boolean", ["feature-state", "hover"], false], 0.85,
            0.55,
          ],
        },
      });
      m.addLayer({ id: "fld-line", type: "line", source: "fields",
        filter: ["==", ["get", "village"], ""],
        paint: { "line-color": "#ffffff", "line-width": 1 } });

      /* click targets - see ClearHarvestMap.jsx for why the state click is
         gated to the two levels where it means anything and bails when a
         field is under the cursor (MapLibre dispatches to every layer under
         the pointer). */
      m.on("click", "pb-fill", (e) => {
        if (levelRef.current !== "india" && levelRef.current !== "punjab") return;
        const overField = m.queryRenderedFeatures(e.point, { layers: ["fld-fill"] });
        if (overField.length) return;
        if (levelRef.current === "punjab") {
          // Ludhiana & Faridkot (pd-fill) is a highlighted sub-area of Punjab
          // with its own click handler below - let that one drive the zoom
          // instead of double-firing here.
          const overDistrict = m.queryRenderedFeatures(e.point, { layers: ["pd-fill"] });
          if (overDistrict.length) return;
        }
        onPickState();
      });
      m.on("mouseenter", "pb-fill", () => {
        if (levelRef.current === "india" || levelRef.current === "punjab") {
          m.getCanvas().style.cursor = "pointer";
        }
      });
      m.on("mouseleave", "pb-fill", () => (m.getCanvas().style.cursor = ""));

      /* project-district (Ludhiana & Faridkot) is its own clickable sub-area:
         - at punjab level, clicking it (not just anywhere on Punjab) drills
           straight into the district step.
         - at district level (both districts already shown, fields tiny at
           that zoom), clicking one district zooms tight into just that
           district's villages so its fields become legible - without
           advancing the level/breadcrumb, since we're still "at district". */
      m.on("click", "pd-fill", (e) => {
        if (levelRef.current === "punjab") {
          e.preventDefault();
          e.originalEvent.stopPropagation();
          onPickState();
        } else if (levelRef.current === "district") {
          const overField = m.queryRenderedFeatures(e.point, { layers: ["fld-fill"] });
          if (overField.length) return; // let the field's own click handler win
          e.preventDefault();
          e.originalEvent.stopPropagation();
          onFocusDistrict(e.features[0].properties.districtName);
        }
      });
      m.on("mouseenter", "pd-fill", () => {
        if (levelRef.current === "punjab" || levelRef.current === "district") {
          m.getCanvas().style.cursor = "pointer";
        }
      });
      m.on("mouseleave", "pd-fill", () => {
        if (levelRef.current === "punjab" || levelRef.current === "district") {
          m.getCanvas().style.cursor = "";
        }
      });

      let hovered = null;
      m.on("mousemove", "fld-fill", (e) => {
        m.getCanvas().style.cursor = "pointer";
        const f = e.features[0];
        if (hovered && hovered !== f.id) m.setFeatureState({ source: "fields", id: hovered }, { hover: false });
        hovered = f.id;
        m.setFeatureState({ source: "fields", id: hovered }, { hover: true });
        onHoverField(f.properties.id);
        popup.current
          .setLngLat(e.lngLat)
          .setHTML(
            `<div style="font-family:${FONT_DATA};font-size:11px;line-height:1.6">
               <div style="font-weight:700;font-size:13px;color:${C.ink}">FARMER ID XXXXX</div>
               <div style="color:${C.mute}">${f.properties.villageName} - XXS ha - ${f.properties.millerName}</div>
             </div>`
          )
          .addTo(m);
      });
      m.on("mouseleave", "fld-fill", () => {
        m.getCanvas().style.cursor = "";
        if (hovered) m.setFeatureState({ source: "fields", id: hovered }, { hover: false });
        hovered = null;
        onHoverField(null);
        popup.current.remove();
      });
      /* clicking bare map (not on a parcel) clears the pin */
      m.on("click", (e) => {
        if (levelRef.current !== "village") return;
        if (m.queryRenderedFeatures(e.point, { layers: ["fld-fill"] }).length) return;
        onPickField(null);
      });

      m.on("click", "fld-fill", (e) => {
        e.preventDefault();                       // don't let it reach pb-fill
        e.originalEvent.stopPropagation();
        const p = e.features[0].properties;
        if (levelRef.current === "district") {
          onZoomToField(p.village, p.id);          // zoom into its village, pinned on arrival
        } else {
          onPickField(p.id);                       // village level: pin it - camera does NOT move
        }
      });

      setReady(true);
    });

    // The map column sits in a CSS grid next to the detail panel, and web
    // fonts/layout can still reflow its width after this effect first runs.
    // resize() alone only re-reads the container's pixel size - it keeps
    // whatever centre/zoom fitBounds computed against the OLD (possibly
    // still-settling) size, which is exactly how India ends up off-centre
    // or cropped. Re-fitting after every resize recomputes that centre/zoom
    // against the container's current size, so India (or whatever level is
    // active) stays properly framed through any later layout shift.
    const ro = new ResizeObserver(() => {
      m.resize();
      refitCamera(m);
    });
    ro.observe(holder.current);

    return () => { ro.disconnect(); m.remove(); map.current = null; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* --- camera + layer visibility per level ------------------------------ */
  useEffect(() => {
    const m = map.current;
    if (!m || !ready) return;

    const showDistrict = level === "district" || level === "village";
    // At the punjab level the district shape (Ludhiana & Faridkot) is its
    // own clickable, highlighted sub-area - not just an outline you can't
    // interact with until you're already past it.
    m.setPaintProperty("pd-fill", "fill-opacity", level === "punjab" ? 0.4 : showDistrict ? 0.14 : 0);
    m.setPaintProperty("pd-line", "line-opacity", level === "punjab" || showDistrict ? 1 : 0);
    m.setPaintProperty("pb-fill", "fill-opacity", level === "india" ? 0.34 : level === "punjab" ? 0.22 : 0.1);

    m.setFilter("fld-fill", showDistrict ? true : ["==", ["get", "village"], ""]);
    m.setFilter("fld-line", showDistrict ? true : ["==", ["get", "village"], ""]);

    refitCamera(m, { duration: 1800 });
  }, [level, village, focusedDistrict, ready, refitCamera]);

  /* --- village pins: small pulsing red dot, one per village --------------
     MapLibre writes its own inline `transform: translate(...)` onto the
     marker's ROOT element to keep it pinned to lng/lat - the halo pulse and
     hover scale live on an inner wrapper instead, or the marker jumps to
     the map's top-left corner the moment either animation touches `el`.
     We deliberately don't bake the village name into the marker (the
     basemap's own place labels sit under it for villages it recognises;
     the clickable name+count legend below the map covers the rest, since
     many of these 126 hamlet-level villages aren't in the basemap at all)
     - a native `title` tooltip gives the name on hover regardless. */
  useEffect(() => {
    const m = map.current;
    if (!m || !ready) return;
    markers.current.forEach((mk) => mk.remove());
    markers.current = [];
    if (level !== "district") return;

    VILLAGES.forEach((v) => {
      const el = document.createElement("div");
      el.style.cssText = "width:16px;height:16px;cursor:pointer;";
      const inner = document.createElement("button");
      inner.setAttribute("aria-label", `${v.name} - XXS fields`);
      inner.title = `${v.name} - XXS fields`;
      inner.style.cssText = `position:relative;width:16px;height:16px;padding:0;border:0;background:none;
        cursor:pointer;display:block;transition:transform .15s ease;`;
      inner.innerHTML = `
        <span style="position:absolute;inset:0;border-radius:99px;background:${C.husk};opacity:.55;
          animation:wh-village-pulse 2.2s ease-out infinite;"></span>
        <span style="position:absolute;top:3px;left:3px;width:10px;height:10px;border-radius:99px;
          background:${C.husk};border:2px solid #fff;box-shadow:0 2px 6px rgba(0,0,0,.45);"></span>`;
      inner.onmouseenter = () => { inner.style.transform = "scale(1.25)"; };
      inner.onmouseleave = () => { inner.style.transform = "none"; };
      inner.onclick = () => onPickVillage(v.key);
      el.appendChild(inner);
      markers.current.push(new Marker({ element: el }).setLngLat([v.lon, v.lat]).addTo(m));
    });
  }, [level, ready, onPickVillage]);

  /* --- selection feature-state ------------------------------------------ */
  const prevSel = useRef(null);
  useEffect(() => {
    const m = map.current;
    if (!m || !ready) return;
    if (prevSel.current) m.setFeatureState({ source: "fields", id: prevSel.current }, { selected: false });
    if (selected) m.setFeatureState({ source: "fields", id: selected }, { selected: true });
    prevSel.current = selected;
  }, [selected, ready]);

  return (
    <div className="relative rounded-lg overflow-hidden" style={{ border: `1px solid ${C.line}` }}>
      <div ref={holder} style={{ width: "100%", height: "clamp(380px, 56vh, 620px)" }} />
      {!ready && (
        <div className="absolute inset-0 flex items-center justify-center" style={{ background: C.paperDim }}>
          <span style={{ fontFamily: FONT_DATA, fontSize: 10.5, letterSpacing: ".12em", color: C.mute }}>
            LOADING BASEMAP...
          </span>
        </div>
      )}
    </div>
  );
}

/* ----------------------------------------------------------------------------
   PANEL + CHROME
---------------------------------------------------------------------------- */
function Row({ k, v, accent }) {
  return (
    <div className="flex justify-between gap-4 py-2" style={{ borderBottom: "1px solid rgba(255,255,255,.1)" }}>
      <span style={{ fontFamily: FONT_DATA, fontSize: 10.5, color: "rgba(255,255,255,.5)", letterSpacing: ".08em" }}>
        {k.toUpperCase()}
      </span>
      <span style={{ fontSize: 13.5, color: accent || "#fff", fontWeight: 600, textAlign: "right" }}>{v}</span>
    </div>
  );
}

function Crumbs({ level, village, onGo }) {
  const trail = [
    { key: "india", label: "India" },
    { key: "punjab", label: "Punjab" },
    { key: "district", label: "Project district" },
  ];
  if (level === "village" && village) {
    trail.push({ key: "village", label: VILLAGES.find((v) => v.key === village)?.name });
  }
  const idx = LEVELS.indexOf(level);
  return (
    <LayoutGroup id="wheat-map-crumbs">
      <div className="flex flex-wrap items-center gap-1.5">
        {trail.map((t, i) => (
          <React.Fragment key={t.key}>
            {i > 0 && <span style={{ color: C.line, fontSize: 11, fontFamily: FONT_DATA }}>/</span>}
            <motion.button
              onClick={() => i <= idx && onGo(t.key)}
              disabled={i > idx}
              className="relative px-2.5 py-1 rounded"
              style={{ fontFamily: FONT_DATA, fontSize: 10.5, letterSpacing: ".08em", fontWeight: 600,
                       color: i === idx ? "#fff" : C.mute, cursor: i <= idx ? "pointer" : "default" }}
            >
              {i === idx && (
                <motion.span layoutId="wheat-map-crumb-pill" className="absolute inset-0 rounded"
                  style={{ background: C.field }} transition={{ type: "spring", stiffness: 380, damping: 32 }} />
              )}
              <span className="relative">{t.label?.toUpperCase()}</span>
            </motion.button>
          </React.Fragment>
        ))}
      </div>
    </LayoutGroup>
  );
}

function Panel({ level, village, field, hoverField }) {
  const v = VILLAGES.find((x) => x.key === village);
  const f = featById(hoverField || field);

  let body;
  if (level === "village" && f) {
    const p = f.properties;
    body = (
      <motion.div key={p.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
        transition={{ duration: 0.28, ease: EASE }}>
        <div className="flex items-center gap-2" style={{ fontFamily: FONT_DATA, fontSize: 11, color: C.husk, letterSpacing: ".18em", fontWeight: 600 }}>
          FARMER FIELD
          {field === p.id && (
            <span style={{ background: C.husk, color: "#fff", borderRadius: 3, padding: "1px 5px", fontSize: 9, letterSpacing: ".1em" }}>
              PINNED
            </span>
          )}
        </div>
        <h3 className="mt-4" style={{ color: "#fff", fontWeight: 700, fontSize: "1.75rem", lineHeight: 1.1 }}>FARMER ID XXXXX</h3>
        <div className="mt-5">
          <Row k="Area" v="XXS ha" accent={C.leaf} />
          <Row k="Village" v={p.villageName} />
          <Row k="Block / Taluka" v={p.block} />
          <Row k="District" v={p.district} />
          <Row k="Procuring miller" v={p.millerName} accent={millerColor(p.millerName)} />
          <Row k="Procurement" v="XXS MT" accent={C.leaf} />
        </div>
      </motion.div>
    );
  } else if (level === "village" && v) {
    body = (
      <motion.div key={v.key} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
        transition={{ duration: 0.28, ease: EASE }}>
        <div style={{ fontFamily: FONT_DATA, fontSize: 11, color: C.husk, letterSpacing: ".18em", fontWeight: 600 }}>
          {v.block.toUpperCase()} BLOCK
        </div>
        <h3 className="mt-4" style={{ color: "#fff", fontWeight: 700, fontSize: "1.75rem" }}>{v.name}</h3>
        <div className="mt-5">
          <Row k="Mapped fields" v="XXS" accent={C.leaf} />
          <Row k="Coordinates" v="XXS°N XXS°E" />
          <Row k="District" v={`${v.district}, Punjab`} />
        </div>
        <p className="mt-5" style={{ fontSize: 13.5, lineHeight: 1.7, color: "rgba(255,255,255,.7)" }}>
          Hover any polygon for the farmer's name and area; click to pin it.
        </p>
      </motion.div>
    );
  } else {
    body = (
      <motion.div key={level} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
        transition={{ duration: 0.28, ease: EASE }}>
        <h3 style={{ color: "#fff", fontWeight: 700, fontSize: "1.75rem", lineHeight: 1.1 }}>
          {level === "india" ? "Where the wheat comes from" : level === "punjab" ? "Punjab" : "Ludhiana & Faridkot"}
        </h3>
        <div className="mt-5">
          <Row k="Mapped fields" v="XXS" accent={C.leaf} />
          <Row k="Villages" v="XXS shown" />
          <Row k="Blocks / talukas" v="XXS" />
          <Row k="Total acreage" v="XXS acres / XXS ha" accent={C.leaf} />
        </div>
      </motion.div>
    );
  }

  return (
    <div className="p-7 md:p-8 rounded-lg h-full" style={{ background: C.ink, minHeight: 420 }}>
      <AnimatePresence mode="wait" initial={false}>{body}</AnimatePresence>
    </div>
  );
}

/* ----------------------------------------------------------------------------
   MAP BLOCK - crumbs + map + legend + panel, no outer <section>/heading, so
   a parent section (e.g. WheatHarvest.jsx's own "Every Field on the Map"
   section) can drop this in next to its own copy/photos without a
   duplicate title.
---------------------------------------------------------------------------- */
export function WheatFieldsMapBlock() {
  const [level, setLevel] = useState("india");
  const [village, setVillage] = useState(null);
  const [field, setField] = useState(null);
  const [hoverField, setHoverField] = useState(null);
  // which of the two (non-adjacent) districts the camera is zoomed into,
  // while still nominally "at" the district level/breadcrumb
  const [focusedDistrict, setFocusedDistrict] = useState(null);

  const goto = useCallback((key) => {
    setLevel(key);
    setField(null);
    setHoverField(null);
    setFocusedDistrict(null);
    if (key !== "village") setVillage(null);
  }, []);

  const pickVillage = useCallback((key) => { setVillage(key); setLevel("village"); setField(null); setFocusedDistrict(null); }, []);
  const pickState = useCallback(() => setLevel((l) => (l === "india" ? "punjab" : "district")), []);
  // clicking a field at district level zooms into its village AND pins that
  // field, so the click actually goes somewhere instead of doing nothing.
  const zoomToField = useCallback((villageKey, fieldId) => {
    setVillage(villageKey); setLevel("village"); setField(fieldId); setFocusedDistrict(null);
  }, []);
  // clicking Ludhiana or Faridkot's shape at district level zooms tight into
  // just that district's villages (fields are illegible specks zoomed out to
  // both districts at once) without leaving the district step.
  const focusDistrict = useCallback((name) => setFocusedDistrict(name), []);
  // "zoom out" backs off the district focus one step before popping levels.
  const zoomOut = useCallback(() => {
    if (level === "district" && focusedDistrict) { setFocusedDistrict(null); return; }
    goto(LEVELS[Math.max(0, LEVELS.indexOf(level) - 1)]);
  }, [level, focusedDistrict, goto]);

  const legend = level === "village"
    ? MILLERS.map((n) => [millerColor(n), n])
    : null;

  return (
    <div>
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
        <Crumbs level={level} village={village} onGo={goto} />
        <AnimatePresence>
          {level !== "india" && (
            <motion.button
              initial={{ opacity: 0, x: 8 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: 8 }}
              onClick={zoomOut}
              className="px-3 py-1.5 rounded"
              style={{ fontFamily: FONT_DATA, fontSize: 10, letterSpacing: ".1em", color: C.mute, border: `1px solid ${C.line}` }}
            >
              &larr; ZOOM OUT
            </motion.button>
          )}
        </AnimatePresence>
      </div>

      <div className="grid gap-6 lg:grid-cols-5 items-stretch">
          <div className="lg:col-span-3">
            <DrillMap
              level={level}
              village={village}
              focusedDistrict={focusedDistrict}
              selected={field}
              onPickState={pickState}
              onPickVillage={pickVillage}
              onPickField={setField}
              onHoverField={setHoverField}
              onZoomToField={zoomToField}
              onFocusDistrict={focusDistrict}
            />

            {legend ? (
              <div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2">
                {legend.map(([c, l]) => (
                  <span key={l} className="flex items-center gap-2" style={{ fontFamily: FONT_DATA, fontSize: 10, color: C.mute }}>
                    <span style={{ width: 10, height: 10, background: c, borderRadius: 2 }} />
                    {l.toUpperCase()}
                  </span>
                ))}
              </div>
            ) : (
              <div className="mt-4 rounded-lg overflow-hidden" style={{ border: `1px solid ${C.line}` }}>
                <div className="grid grid-cols-2" style={{ background: C.field }}>
                  <div className="px-4 py-2" style={{ fontFamily: FONT_DATA, fontSize: 10.5, color: "#fff", fontWeight: 700, letterSpacing: ".08em" }}>MILLER</div>
                  <div className="px-4 py-2 text-right" style={{ fontFamily: FONT_DATA, fontSize: 10.5, color: "#fff", fontWeight: 700, letterSpacing: ".08em" }}>IN MT</div>
                </div>
                {MILLER_ORDER.map((n, i) => (
                  <div key={n} className="grid grid-cols-2" style={{ borderTop: i ? `1px solid ${C.line}` : "none", background: i % 2 ? C.paperDim : "#fff" }}>
                    <div className="px-4 py-2.5 flex items-center gap-2" style={{ fontFamily: FONT_DATA, fontSize: 12, color: C.ink, fontWeight: 600 }}>
                      <span style={{ width: 9, height: 9, background: millerColor(n), borderRadius: 2, flexShrink: 0 }} />
                      {n}
                    </div>
                    <div className="px-4 py-2.5 text-right" style={{ fontFamily: FONT_DATA, fontSize: 12, color: C.mute }}>
                      XXS
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div className="lg:col-span-2">
            <Panel level={level} village={village} field={field} hoverField={hoverField} />
          </div>
        </div>
    </div>
  );
}

/* ----------------------------------------------------------------------------
   SECTION - standalone drop-in section (heading + WheatFieldsMapBlock), for
   use if this ever needs to live outside WheatHarvest.jsx's own section.
---------------------------------------------------------------------------- */
export default function WheatLocationSection() {
  return (
    <section id="location" className="px-5 md:px-10 py-20 md:py-28" style={{ background: C.paper }}>
      <div className="mx-auto" style={{ maxWidth: 1180 }}>
        <div className="mb-10 md:mb-14">
          <div className="flex items-baseline gap-4">
            <span style={{ fontFamily: FONT_DATA, fontSize: 13, color: C.husk, fontWeight: 600 }}>02</span>
            <span style={{ flex: 1, height: 1, background: C.line }} />
          </div>
          <h2 className="mt-4" style={{ color: C.field, fontWeight: 800, fontSize: "clamp(1.9rem,4vw,3rem)", letterSpacing: "-.03em", lineHeight: 1, maxWidth: "22ch" }}>
            Every field on the map
          </h2>
          <p className="mt-5" style={{ color: C.mute, maxWidth: "62ch", lineHeight: 1.65, fontSize: "1.05rem" }}>
            The programme ran across XXS villages in Ludhiana and Faridkot, Punjab. All XXS{" "}
            enrolled farmer fields were geo-tagged - click Punjab to drill from the country down to a single plot.
          </p>
        </div>
        <WheatFieldsMapBlock />
      </div>
    </section>
  );
}
